imapadmin.imapserver.*:
  type: config_entity
  label: 'IMAP server'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    hostname:
      type: string
      label: 'Hostname'
    encryption:
      type: string
      label: 'Encryption'
    validate_cert:
      type: boolean
      label: 'Validate certificate'
    port:
      type: integer
      label: 'TCP port'
    username:
      type: string
      label: 'Username'
    password:
      type: string
      label: 'Password'
